service: neoarxiv-api
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  logRetentionInDays: 30
  apiGateway:
    minimumCompressionSize: 0
    binaryMediaTypes:
      - '*/*'
  environment:
    AUTH_SECRET: ${file(./.config.json):AUTH_SECRET}

functions:
  api:
    handler: app/handler.handler
    events:
      - http:
          method: any
          path: /{proxy+}
  newArxiv:
    handler: cron/newArxiv.handler
    # events:
    #   - schedule: rate(2 hours)
  bioRxiv:
    handler: cron/bioRxiv.handler
    # events:
    #   - schedule: rate(2 hours)

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk